### ISSUE TITLE
Updates releases

### ISSUE THREAD

**Issue by 1Jesper1** [jsakamoto/AntiVirusScanner#6]
Hello, I see there also exist a version 1.0.0 and a 1.0.2? Could you create a release for these at https://github.com/jsakamoto/AntiVirusScanner/releases? So we can see what has been changed.

**Comment by jsakamoto** [comment]
@1Jesper1 Thank you for contacting me. I created each lacked release page. Please check it out.

**Comment by 1Jesper1** [comment]
Thanks!
